Repository uniorunr/culture-portal, pull requests merged in 2019-07, with the labels that each got.

#7 Main page grid layout
  .gitignore
  gatsby-config.js
  package.json
  src/pages/index.js
  src/scss/main.scss
Labels: enhancement

#13 #6 feature add eslint and editorconfig to the project
  .editorconfig
  .eslintrc.js
  package.json
Labels: enhancement

#23 fix media query in search.scss
  src/scss/search.scss
Labels: asap, bug

#24 Author page layout
  src/pages/author.js
  src/scss/author.scss
Labels: enhancement, good to implement it faster

#27 Add Header component
  src/components/Header.js
  src/pages/index.js
  src/scss/author.scss
  src/scss/colors.scss
  src/scss/generic.scss
  src/scss/main.scss
Labels: enhancement

#26 #19 feature add director of day component component
  src/components/culturePortalInfo/culturePortalInfo.js
  src/components/culturePortalInfo/culturePortalInfo.scss
  src/components/directorCard/directorCard.js
  src/components/directorCard/directorCard.scss
  src/components/directorCard/index.js
  src/pages/index.js
  src/scss/author.scss
  src/scss/main.scss
  src/scss/search.scss
Labels: enhancement

#32 Update Header component to display curr lang option
  .babelrc
  .eslintrc.js
  package.json
  src/components/Header/Header.js
  src/pages/index.js
Labels: asap, enhancement

#34 Header component: show only inactive lang options
  src/components/Header/Header.js
Labels: asap, enhancement

#39 #38 feature add support of react i18next
  package.json
  src/components/Header/Header.js
  src/language/index.js
  src/pages/index.js
Labels: enhancement

#35 Add Footer component
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Header/Header.js
  src/components/directorCard/directorCard.js
  src/components/directorCard/directorCard.scss
  src/components/gitHubProfile/gitHubProfile.js
  src/components/gitHubProfile/gitHubProfile.scss
  src/pages/index.js
  src/scss/main.scss
Labels: enhancement

#45 #41 feat add photo gallery with author's picture
  package.json
  src/components/photoGallery/index.js
  src/components/photoGallery/style.scss
  src/pages/author.js
  static/1.jpg
  static/2.jpg
  static/3.jpg
  static/4.jpg
Labels: enhancement, good to implement it faster
