Repository uniorunr/culture-portal, pull requests merged in 2019-08, with the labels that each got.

#49 #14 feature create design
  src/components/Footer/Footer.scss
  src/components/Header/Header.js
  src/components/Header/header.scss
  src/components/Header/logo.png
  src/components/directorCard/directorCard.js
  src/components/directorCard/directorCard.scss
  src/components/gitHubProfile/gitHubProfile.js
  src/components/gitHubProfile/gitHubProfile.scss
  src/pages/index.js
  src/scss/colors.scss
  src/scss/generic.scss
  src/scss/main.scss
Labels: asap, enhancement

#59 Implement Gatsby Layout; Fully implement search page functionality
  gatsby-config.js
  package.json
  src/components/DirectorCardSearch/DirectorCardSearch.js
  src/components/Header/Header.js
  src/layouts/index.js
  src/pages/author.js
  src/pages/index.js
  src/pages/search.js
  src/scss/search.scss
Labels: asap, enhancement

#66 Add List of works component
  src/components/DirectorWorks/DirectorWorks.js
  src/language/index.js
  src/pages/author.js
  src/scss/author.scss
Labels: enhancement, good to implement it faster

#68 Footer redesign, fix links in Footer
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/gitHubProfile/gitHubProfile.js
  src/components/gitHubProfile/gitHubProfile.scss
  src/language/index.js
Labels: enhancement

#71 #69 fix map
  src/components/map/map.js
  src/components/map/map.scss
  src/pages/author.js
  src/scss/author.scss
Labels: bug

#74 fix Footer: change prop type of name prop
  src/components/gitHubProfile/gitHubProfile.js
Labels: bug

#76 #75/fix: fix build error
  src/pages/author.js
Labels: asap

#78 #77/fix: fix error author page
  src/pages/author.js
Labels: bug

#80 #79/fix: fix first show directorCard
  src/components/directorCard/directorCard.js
Labels: bug

#83 add project info to README
  README.md
Labels: documentation

#85 Add custom favicon
  .vscode/settings.json
  gatsby-config.js
  package.json
  src/favicon.png
Labels: enhancement

#81 feat: add new main color and fix bug with author page redirect
  README.md
  src/components/DirectorCardSearch/DirectorCardSearch.scss
  src/components/DirectorWorks/DirectorWorks.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Header/Header.js
  src/components/Header/header.scss
  src/components/Header/logo.png
  src/components/authorInfo/authorInfo.js
  src/components/directorCard/directorCard.scss
  src/components/gitHubProfile/gitHubProfile.scss
  src/components/timeline/TimelineContainer.js
  src/language/index.js
  src/pages/author.js
  src/scss/author.scss
  src/scss/main.scss
Labels: question
